### ISSUE TITLE
site doesn't handle hyphens in URLs

### ISSUE THREAD

**Issue by lachlanhardy** [webjam/webjam#1]
See http://webjam.com.au/people/pseudo-si

**Comment by lstoll** [comment]
Removing strip_permalinks - only applied to user controller, and was breaking users with a hyphen. It seems to have no other function than this, and this is now a bug. It pre-dates commit history on site, so can't be sure why it existed. Closed by 3bdebbfa21bac081135135db801c00d52b92e467
